### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by tinalin923**
我是林怡君(YJLin)

http://34.195.43.91:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Your code will repeating call API and failed, after last page loaded. Fix it and leave comment for me to review again.

未命名-2

**Comment by tinalin923** [comment]
I've fixed the problem. Thanks!
http://34.195.43.91:3000/

**Review by cwpeng — APPROVED** [review]
OK. Basically Done.

Suggestion: try to use a global variable to track API loading status. Set it to true if API is loading, to false if end of loading. Use it to make sure there is only one API loading at the same time.

**Comment by tinalin923** [comment]
I've tried to use a global variable to track API loading status. But I'm not sure about that.
Please check again, thanks. 

http://34.195.43.91:3000/

**Pull request merged**
